### ISSUE TITLE
BOM inaccuracies

### ISSUE THREAD

**Issue by phifisch** [janelia-experimental-technology/RGB-IR-LED-Boards#1]
Hello,

Thank you for your great work. I stumbled upon a few issues in the BOM when trying to have the board manufactured. For one U24 occurs twice. The second occurrence is the digital isolator, and should be changed to U22 to fit the schematic and placement file.
Also, U25, a 3.3V regulator  is mentioned only in the BOM, but does not appear in neither the schematic not the board design itself. Am I right to assume that the 3.3V rail is supposed to be supplied bythe Teensy board alone (so ultimately via the USB port?), and so a 3.3V regulator would be obsolete?

Cheers,
Phil

**Comment by sawtelles** [comment]
I’ll check into that. Thanks for letting me know.
-Steve

On Apr 17, 2024, at 6:14 AM, phifisch ***@***.***> wrote:

﻿
External Email: Use Caution



Hello,

Thank you for your great work. I stumbled upon a few issues in the BOM when trying to have the board manufactured. For one U24 occurs twice. The second occurrence is the digital isolator, and should be changed to U22 to fit the schematic and placement file.
Also, U25, a 3.3V regulator is mentioned only in the BOM, but does not appear in neither the schematic not the board design itself. Am I right to assume that the 3.3V rail is supposed to be supplied bythe Teensy board alone (so ultimately via the USB port?), and so a 3.3V regulator would be obsolete?

Cheers,
Phil

**Comment by sawtelles** [comment]
Hi Phil,

Fixed. Thanks for pointing it out!

I also added board specs – we use a 0.8mm board with 2oz copper with a white soldermask and black silkscreen. If you assemble the board yourself, you can order blank boards easily from Oshpark.

Also, you can use whatever colors you want for the LEDs as the package we use is available in many varieties. We have done RGB, red-green-green, deep red, etc.

Steve Sawtelle
Electrical Engineer
jET
Janelia, HHMI
19700 Helix Dr
Ashburn, VA  20147



From: phifisch ***@***.***>
Sent: Wednesday, April 17, 2024 6:14 AM
To: janelia-experimental-technology/RGB-IR-LED-Boards ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [janelia-experimental-technology/RGB-IR-LED-Boards] BOM inaccuracies (Issue #1)

External Email: Use Caution


Hello,

Thank you for your great work. I stumbled upon a few issues in the BOM when trying to have the board manufactured. For one U24 occurs twice. The second occurrence is the digital isolator, and should be changed to U22 to fit the schematic and placement file.
Also, U25, a 3.3V regulator is mentioned only in the BOM, but does not appear in neither the schematic not the board design itself. Am I right to assume that the 3.3V rail is supposed to be supplied bythe Teensy board alone (so ultimately via the USB port?), and so a 3.3V regulator would be obsolete?

Cheers,
Phil

**Comment by phifisch** [comment]
Hi,
I forgot to feedback. Thanks for clarifying! Incidentally, thanks for adding the 7x7 as well.
Phil
